spring:
  datasource:
    name: tennisCourts
    url: 'jdbc:h2:~/tennisCourts'
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: non_null

logging:
  level:
    org:
      hibernate:
        type: trace

pagination:
  size: 10
  direction: ASC
  page: 0
